.PHONY: install test lint figures train eval

install:
	conda env create -f environment.yml
	conda run -n mdr pip install -e .

test:
	conda run -n mdr pytest tests/ -v

lint:
	conda run -n mdr black --check src/ tests/
	conda run -n mdr flake8 src/ tests/ --max-line-length=100

train:
	conda run -n mdr python src/pipeline/main.py

eval:
	@echo "Run the evaluation notebook: notebooks/training/MDR-v24.ipynb"

figures:
	@echo "Figures are generated by the training notebooks in notebooks/training/"
	@echo "Results are saved to results/figures/"
