#!/usr/bin/env python
"""Audit Touchet_WA_824 data completeness across versioned split CSVs.

Reproducible audit used to answer:

    "Was the Touchet_WA_824 multi-year gap (zero entries 2021-2023) newly
     introduced since derived_8.1, or has it always been there?"

The script discovers every split version under ``data/splits/`` (including
``archive/``), counts Touchet rows per split part and per calendar year, and
prints markdown tables that are copied verbatim into
``docs/audits/touchet-data-audit.md``.

Run (from anywhere; repo root is resolved relative to this file):

    uv run --project notebooks python docs/audits/audit_touchet_data.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

STATION = "Touchet_WA_824"
PARTS = ("train", "val", "test")
YEARS = range(2011, 2026)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def discover_split_dirs(splits_root: Path) -> list[tuple[str, Path]]:
    """Return (display_name, dir) for every dir containing train/val/test CSVs."""
    found: list[tuple[str, Path]] = []
    for base in (splits_root, splits_root / "archive"):
        if not base.exists():
            continue
        for child in sorted(base.iterdir()):
            if child.is_dir() and all((child / f"{p}.csv").exists() for p in PARTS):
                name = child.name if base == splits_root else f"archive/{child.name}"
                found.append((name, child))
    return found


def load_split(dir_path: Path, part: str) -> pd.DataFrame:
    """Load a split CSV keeping only station_id and date."""
    df = pd.read_csv(dir_path / f"{part}.csv", usecols=["station_id", "date"])
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    return df


def rows_by_year(df: pd.DataFrame) -> pd.Series:
    return df["date"].dt.year.dropna().astype(int).value_counts().sort_index()


def main() -> None:
    splits_root = repo_root() / "data" / "splits"
    versions = discover_split_dirs(splits_root)

    # ---- Table 1: Touchet rows per split part per version ----
    print("# Touchet_WA_824 data completeness audit")
    print()
    print("Generated by `uv run --project notebooks python docs/audits/audit_touchet_data.py`")
    print()
    print("## Table 1. Touchet_WA_824 rows per split part, by dataset version")
    print()
    print("| Version | train | val | test | total |")
    print("|---|---:|---:|---:|---:|")
    summary: dict[str, dict[str, int]] = {}
    for name, d in versions:
        counts: dict[str, int] = {"train": 0, "val": 0, "test": 0}
        try:
            for p in PARTS:
                df = load_split(d, p)
                counts[p] = int((df["station_id"].astype(str) == STATION).sum())
        except Exception as exc:  # noqa: BLE001 - report and continue
            print(f"| {name} | *skipped ({exc})* | | | |")
            continue
        total = sum(counts.values())
        summary[name] = counts
        print(f"| {name} | {counts['train']} | {counts['val']} | {counts['test']} | {total} |")
    print()

    # ---- Table 2: Touchet rows per calendar year (train+val+test combined) ----
    print("## Table 2. Touchet_WA_824 rows per calendar year (all parts combined)")
    print()
    header = "| Version |" + "".join(f" {y} |" for y in YEARS) + " total |"
    sep = "|---|" + "---|" * len(YEARS) + "---|"
    print(header)
    print(sep)
    yearly: dict[str, dict[int, int]] = {}
    for name, d in versions:
        if name not in summary:
            continue
        year_counts: dict[int, int] = {}
        try:
            frames = [load_split(d, p) for p in PARTS]
            for df in frames:
                tou = df[df["station_id"].astype(str) == STATION]
                for y, n in rows_by_year(tou).items():
                    year_counts[int(y)] = int(n)
        except Exception as exc:  # noqa: BLE001
            print(f"| {name} | *skipped ({exc})* |")
            continue
        yearly[name] = year_counts
        row = f"| {name} |" + "".join(
            f" {year_counts.get(y, 0)} |" for y in YEARS
        ) + f" {sum(year_counts.values())} |"
        print(row)
    print()

    # ---- Table 3: derived_8.0 station x year matrix (context: 5 original stations) ----
    print("## Table 3. derived_8.0: rows per station per year (the original 5-station split)")
    print()
    d80 = splits_root / "derived_8.0"
    if d80.exists():
        frames = [load_split(d80, p) for p in PARTS]
        full = pd.concat(frames, ignore_index=True)
        matrix = (
            full.assign(year=full["date"].dt.year.astype(int))
            .groupby(["station_id", "year"])
            .size()
            .unstack(fill_value=0)
        )
        # Keep a stable column order and only the years present in the split
        cols = [c for c in range(2017, 2026) if c in matrix.columns]
        print("| station_id |" + "".join(f" {c} |" for c in cols) + " total |")
        print("|---|" + "---|" * len(cols) + "---|")
        for sid, row in matrix.iterrows():
            cells = "".join(f" {int(row[c])} |" for c in cols)
            print(f"| {sid} |{cells} {int(row[cols].sum())} |")
    else:
        print("(derived_8.0 not found)")
    print()

    # ---- Table 4: effect of the derived_8.1_pos target filter (train) ----
    print("## Table 4. derived_8.1 train: effect of the `soil_moisture_5cm > 0.0` filter")
    print("(applied in derived_8.1_pos and inherited by derived_8.2)")
    print()
    d81 = splits_root / "derived_8.1"
    if d81.exists():
        train = pd.read_csv(d81 / "train.csv", usecols=["station_id", "soil_moisture_5cm"])
        before = train.groupby("station_id").size()
        after = train[train["soil_moisture_5cm"] > 0.0].groupby("station_id").size()
        print("| station_id | rows before | rows after | retention % |")
        print("|---|---:|---:|---:|")
        for sid in sorted(before.index):
            b, a = int(before[sid]), int(after.get(sid, 0))
            pct = 100.0 * a / b if b else 0.0
            print(f"| {sid} | {b} | {a} | {pct:.1f}% |")
    else:
        print("(derived_8.1 not found)")
    print()

    # ---- Footnotes on versions without Touchet ----
    absent = [name for name, counts in summary.items() if sum(counts.values()) == 0]
    if absent:
        print("## Note")
        print()
        print("Versions with zero Touchet rows (removed or not yet added): "
              + ", ".join(f"`{n}`" for n in absent) + ".")
        print()


if __name__ == "__main__":
    sys.exit(main())
