"""Tests for the no-SMAP model-salvage experiment."""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import yaml


PROJECT_ROOT = Path(__file__).resolve().parents[1]
EXP_DIR = PROJECT_ROOT / "notebooks/experiment/derived_8.4-ece-model-salvage-1.0"
RUNNER_PATH = EXP_DIR / "run_model_salvage.py"


def _runner():
    spec = importlib.util.spec_from_file_location("ece_model_salvage_test_runner", RUNNER_PATH)
    if spec is None or spec.loader is None:
        raise ImportError(RUNNER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_config_has_all_requested_model_families_and_seeds():
    config = yaml.safe_load((EXP_DIR / "config.yaml").read_text(encoding="utf-8"))
    assert config["seeds"] == [42, 7, 13, 101, 123]
    assert len(config["models"]) == 7
    assert {model["id"] for model in config["models"]} == {
        "Clustering_V0_Full_k2_no_smap",
        "Clustering_Backbone54_k2_no_smap",
        "Trained_Gating_k2_no_smap",
        "Univariate_G_API_k2_no_smap",
        "Clustering_Dynamic_k2_no_smap",
        "Seasonal_Binary_k2_no_smap",
        "Global_Single_54_no_smap",
    }


def test_drop_smap_removes_every_case_variant():
    runner = _runner()
    assert runner.drop_smap(["G_API", "SMAP_x", "smap_lag", "LST_modis"]) == ["G_API", "LST_modis"]


def test_metric_includes_level_and_first_difference_trend_scores():
    runner = _runner()
    frame = pd.DataFrame({
        "station_id": ["a"] * 4,
        "date": pd.to_datetime(["2025-07-20", "2025-07-21", "2025-07-22", "2025-07-23"]),
        "target": [0.10, 0.09, 0.075, 0.07],
        "prediction": [0.11, 0.10, 0.085, 0.08],
    })
    metrics = runner.compute_metrics(frame)
    assert metrics["rmse"] > 0
    assert metrics["pearson"] == pytest.approx(1.0)
    assert metrics["diff_pearson"] == pytest.approx(1.0)
    assert metrics["prediction_std"] == pytest.approx(metrics["target_std"])


def test_requested_router_feature_sets_are_smap_free():
    runner = _runner()
    config = runner.load_configuration()
    dynamic = runner.drop_smap(config["features"]["dynamic_parent"])
    assert dynamic == ["G_API", "LST_modis"]
    assert all("smap" not in feature.lower() for feature in dynamic)


def test_canonical_feature_counts_match_strict_smap_removal():
    data_dir = PROJECT_ROOT / "data/splits/derived_8.4"
    if not (data_dir / "train.csv").exists():
        pytest.skip("Repository data are not hydrated.")
    runner = _runner()
    data = runner.load_data(runner.load_configuration())
    assert len(data.v0_parent) == 50
    assert len(data.v0_features) == 42
    assert len(data.backbone_parent) == 54
    assert len(data.backbone_features) == 42


def test_special_gates_are_deterministic_and_two_regime():
    runner = _runner()
    from eval_formal.routers import SeasonalBinaryRouter, UnivariateGAPIRouter

    frame = pd.DataFrame({"G_API": [0.1, 0.9], "month": [7, 12]})
    gapi = UnivariateGAPIRouter("G_API").fit(frame)
    seasonal = SeasonalBinaryRouter().fit(frame)
    assert np.array_equal(gapi.predict(frame), np.array([0, 1]))
    assert np.array_equal(seasonal.predict(frame), np.array([0, 1]))


def test_generated_outputs_have_complete_coverage_when_present():
    summary_path = EXP_DIR / "summary.csv"
    seed_metrics_path = EXP_DIR / "seed_metrics.csv"
    if not summary_path.exists() or not seed_metrics_path.exists():
        pytest.skip("Full experiment outputs are generated by the GPU job.")
    summary = pd.read_csv(summary_path, low_memory=False)
    seed_metrics = pd.read_csv(seed_metrics_path, low_memory=False)
    expected_models = {
        "Clustering_V0_Full_k2_no_smap",
        "Clustering_Backbone54_k2_no_smap",
        "Trained_Gating_k2_no_smap",
        "Univariate_G_API_k2_no_smap",
        "Clustering_Dynamic_k2_no_smap",
        "Seasonal_Binary_k2_no_smap",
        "Global_Single_54_no_smap",
    }
    if set(seed_metrics["seed"]) != {42, 7, 13, 101, 123}:
        pytest.skip("Only smoke outputs are present; full five-seed job has not completed.")
    assert set(seed_metrics["model_id"]) == expected_models
    pooled = summary[summary["scope"] == "__pooled__"]
    assert set(pooled["model_id"]) == expected_models
    assert set(pooled["window"]) == {"temporal_full", "temporal_summer_2025", "spatial_ece_v3_full"}


def test_smap_invariance_output_is_zero_when_present():
    path = EXP_DIR / "smap_invariance.csv"
    if not path.exists():
        pytest.skip("Full experiment outputs are generated by the GPU job.")
    invariance = pd.read_csv(path)
    assert len(invariance) == 7
    assert (invariance["max_abs_prediction_difference"] <= 1e-12).all()
    assert (invariance["changed_regime_labels"] == 0).all()


def test_readme_figure_links_include_figure_directory_when_present():
    readme_path = EXP_DIR / "README.md"
    if not readme_path.exists():
        pytest.skip("Report README is generated after notebook execution.")
    readme = readme_path.read_text(encoding="utf-8")
    image_targets = re.findall(r"!\[[^]]+\]\(([^)]+)\)", readme)
    figure_targets = [target for target in image_targets if target.endswith(".png")]
    assert figure_targets
    assert all(target.startswith("figures/") for target in figure_targets)
    assert all((EXP_DIR / target).exists() for target in figure_targets)
