pipeline:
  request:
    base_url: "https://www.ncei.noaa.gov/pub/data/uscrn/products/daily01" # UPDATE
    station: "WA_Spokane_17_SSW" # UPDATE
    start_year: 2007 # < 2007 = non existent data
    end_year: 2025
    timeout: 20
    min_bytes: 500
    out_dir: "data/spokane/raw" # UPDATE

  parse:
    in_dir: data/spokane/raw
    out_dir: data/spokane/processed
    drop_duplicates: true
    col_indices:
      station_id: 0 # WBANNO
      date: 1 # DATE (YYYYMMDD)
      crx_vn: 2 # CRX_VN  (station/version)
      longitude: 3 # LONGITUDE (decimal degrees, already negative for W)
      latitude: 4 # LATITUDE  (decimal degrees)
      air_temp_max: 5 # TEMP_DAILY_MAX (°C)
      air_temp_min: 6 # TEMP_DAILY_MIN (°C)
      air_temp_mean: 7 # TEMP_DAILY_MEAN (°C)
      air_temp_avg: 8 # TEMP_DAILY_AVG (°C)
      precipitation: 9 # PERCIP_DAILY_CALC (mm)
      solar_radiation: 10 # SOLAR_RAD_DAILY (MJ/m^2)
      sur_temp_type: 11 # SURFACE_TEMP_DAILY_TYPE (R/C/U)
      sur_temp_max: 12 # SURFACE_TEMP_DAILY_MAX (°C)
      sur_temp_min: 13 # SURFACE_TEMP_DAILY_MIN (°C)
      sur_temp_avg: 14 # SURFACE_TEMP_DAILY_AVG (°C)
      rh_max: 15 # RELATIVE_HUMIDITY_DAILY_MAX (%)
      rh_min: 16 # RELATIVE_HUMIDITY_DAILY_MIN (%)
      rh_mean: 17 # RELATIVE_HUMIDITY_DAILY_AVG (%)
      soil_moisture_5cm: 18 # SOIL_MOISTURE_5_DAILY (m^3/m^3)
      soil_moisture_10cm: 19
      soil_moisture_20cm: 20
      soil_moisture_50cm: 21
      soil_moisture_100cm: 22
      soil_temp_5cm: 23 # SOIL_TEMP_5_DAILY (°C)
      soil_temp_10cm: 24
      soil_temp_20cm: 25
      soil_temp_50cm: 26
      soil_temp_100cm: 27

  clean:
    drop_missing: true
    fillna_value: null
    keep_columns: [] # == KEEP ALL, configure later

  merge:
    on_columns: ["station_id", "date"]
    how: "outer"

  save:
    out_path: "data/processed/spokane/final.csv" # UPDATE
    format: "csv"
    index: false

  temporal_fill:
    target_columns:
      - soil_moisture_5cm
      - soil_moisture_10cm
      - soil_moisture_20cm
      - soil_moisture_50cm
      - soil_moisture_100cm
      - air_temp_mean
      - rh_mean
      - solar_radiation
      - sur_temp_avg
    max_gap_days: 5
    switch_gap: 4
    regression_window: 7

  satellite:
    cache_path: "Pipeline/data/cache/satellite_cache.json"

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  file_path: "logs/pipeline.log"
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  max_bytes: 10485760 # 10 MB
  backup_count: 5
