[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline"
version = "0.1.0"
description = "Soil moisture modeling data processing pipeline sub-project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy",
    "pandas",
    "requests",
    "scipy",
    "scikit-learn",
    "tqdm",
    "xgboost",
    "pyyaml",
    "earthengine-api",
    "matplotlib",
]

[tool.setuptools]
packages = ["pipeline"]
package-dir = {"pipeline" = "."}
